#######################################
#
# インフラで利用する環境変数のtemplate
#
#######################################
#######################################
# settings
#######################################
AWS_REGION: ap-northeast-1
AWS_CLI_PROFILE: 'stingy'
#######################################
# cloud front
#######################################
CLOUDFRONT_DYNAMIC_CACHE_POLICY_NAME: chillnn-training-front-dynamic-cache-policy-${self:provider.stage}
CLOUDFRONT_STATIC_CACHE_POLICY_NAME: chillnn-training-front-static-cache-policy-${self:provider.stage}
CLOUDFRONT_ALIASES:
    - ${self:provider.stage}.chillnn-training.stingy.ch
CLOUDFRONT_ALIAS_ACM_ARN: 'arn:aws:acm:us-east-1:334547292678:certificate/04e44d94-0eb7-4d7f-ad58-fc5c9fbd1ef7'
#######################################
# s3
#######################################
S3_BUCKET_NAME: 'chillnn-training-front-nuxt-${self:provider.stage}'
