projects:
  chillnn-training-user-dev:
    schemaPath: client/driver/amplify/graphql/schema.json
    includes:
      - client/driver/amplify/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: client/driver/amplify/graphql/API.ts
        docsFilePath: client/driver/amplify/graphql
        region: ap-northeast-1
        apiId: ln4yq2sonrdwjbnkyt5cex5rky
        maxDepth: 5
extensions:
  amplify:
    version: 3
